packageExtensions:
  "@docusaurus/mdx-loader@*":
    peerDependencies:
      react: ^16.13.1
      react-dom: ^16.8.4
      webpack: ^4.0.0 || ^5.0.0
  "@docusaurus/plugin-content-blog@*":
    peerDependencies:
      webpack: ^4.0.0 || ^5.0.0
  "@docusaurus/plugin-content-docs@*":
    peerDependencies:
      webpack: ^4.0.0 || ^5.0.0
  "@docusaurus/plugin-content-pages@*":
    peerDependencies:
      webpack: ^4.0.0 || ^5.0.0
  "@docusaurus/preset-classic@*":
    peerDependencies:
      "@docusaurus/utils": 2.0.0-alpha.61
      webpack: ^4.0.0 || ^5.0.0

yarnPath: .yarn/releases/yarn-sources.cjs
