yarnPath: ".yarn/releases/yarn-berry.js"
packageExtensions:
  "@docusaurus/mdx-loader@*":
    peerDependencies:
      webpack: ^4.0.0 || ^5.0.0
      react: ^16.13.1
  "@docusaurus/preset-classic@*":
    peerDependencies:
      "@docusaurus/utils": 2.0.0-alpha.60
