yarnPath: ".yarn/releases/yarn-berry.js"
packageExtensions:
  "@docusaurus/mdx-loader@*":
    peerDependencies:
      webpack: ^4.0.0 || ^5.0.0
      react: ^16.13.1
      react-dom: ^16.8.4
  "@docusaurus/preset-classic@*":
    peerDependencies:
      webpack: ^4.0.0 || ^5.0.0
      "@docusaurus/utils": 2.0.0-alpha.61
  "@docusaurus/plugin-content-blog@*":
    peerDependencies:
      webpack: ^4.0.0 || ^5.0.0
  "@docusaurus/plugin-content-docs@*":
    peerDependencies:
      webpack: ^4.0.0 || ^5.0.0
  "@docusaurus/plugin-content-pages@*":
    peerDependencies:
      webpack: ^4.0.0 || ^5.0.0
